---
name: build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1

      - name: Install Node.js
        uses: actions/setup-node@master
        with:
          node-version: '12.x'

      - name: Run test
        run: |
          npm install
          npm test
